global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "betsafe-gateway"
    metrics_path: "/actuator/prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["betsafe-gateway:8090"]
        labels:
          application: "betsafe-gateway"

  - job_name: "betsafe-flink"
    scrape_interval: 15s
    static_configs:
      - targets:
          - "flink-jobmanager:9249"
          - "flink-taskmanager-1:9249"
          - "flink-taskmanager-2:9249"
        labels:
          application: "betsafe-flink"
